### ISSUE TITLE
MongoError: no mongos proxy available at Timeout.<anonymous> 

### ISSUE THREAD

**Issue by mekka-logic** [bradtraversy/node_passport_login#32]
Server started on port 5000
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (D:\Mayka\Lab\node_passport_login-master\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\mongos.js:757:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }

**"Need your advise for above problem..."**

**Comment by bradtraversy** [comment]
Closing as part of stale issue cleanup. This appears to be a MongoDB connection/configuration issue rather than a repo bug. The repo has also since been updated. If this still happens against latest master with a valid Mongo URI, please open a fresh issue with updated reproduction steps.
