### ISSUE TITLE
{ MongoNetworkError: failed to connect to server [test-cluster1-shard-00-02-ioe1x.mongodb.net:27017]

### ISSUE THREAD

**Issue by ericdvlpr** [bradtraversy/node_passport_login#46]
{ MongoNetworkError: failed to connect to server [test-cluster1-shard-00-02-ioe1x.mongodb.net:27017] on first connect [MongoError: bad auth Authentication failed.]
    at Pool.<anonymous> (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\topologies\server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\connection\pool.js:557:14)
    at callback (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\connection\connect.js:109:5)
    at provider.auth.err (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\connection\connect.js:352:21)
    at _authenticateSingleConnection (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\auth\auth_provider.js:66:11)
    at sendAuthCommand (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\auth\scram.js:215:18)
    at Connection.messageHandler (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\connection\connect.js:334:5)
    at Connection.emit (events.js:198:13)
    at processMessage (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (C:\xampp\htdocs\nodejs_authentication\node_modules\mongodb-core\lib\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by sagar608** [comment]
Make sure you check your databse uri
