### ISSUE TITLE
Error: No default engine was specified and no extension was provided.     at new View (D:\Node_Passport\node_modules\express\lib\view.js:61:

### ISSUE THREAD

**Issue by kinkeyluja** [bradtraversy/node_passport_login#96]
Error: No default engine was specified and no extension was provided.
    at new View (D:\Node_Passport\node_modules\express\lib\view.js:61:11)
    at Function.render (D:\Node_Passport\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (D:\Node_Passport\node_modules\express\lib\response.js:1012:7)
    at D:\Node_Passport\routes\index.js:4:35
    at Layer.handle [as handle_request] (D:\Node_Passport\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Node_Passport\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Node_Passport\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Node_Passport\node_modules\express\lib\router\layer.js:95:5)
    at D:\Node_Passport\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Node_Passport\node_modules\express\lib\router\index.js:335:12)
Error: No default engine was specified and no extension was provided.
    at new View (D:\Node_Passport\node_modules\express\lib\view.js:61:11)
    at Function.render (D:\Node_Passport\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (D:\Node_Passport\node_modules\express\lib\response.js:1012:7)
    at D:\Node_Passport\routes\index.js:4:35
    at Layer.handle [as handle_request] (D:\Node_Passport\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Node_Passport\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Node_Passport\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Node_Passport\node_modules\express\lib\router\layer.js:95:5)
    at D:\Node_Passport\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Node_Passport\node_modules\express\lib\router\index.js:335:12)

**Comment by bradtraversy** [comment]
Closing as part of stale issue cleanup. The repo has since been updated with current EJS syntax and dependency/security fixes, so this issue is likely obsolete. If this still happens against the latest master, please open a fresh issue with updated reproduction steps.
